//
//  Constant.h
//  OxyFryer
//
//  Created by Richa Goyal on 9/17/14.
//  Copyright (c) 2014 Richa Goyal. All rights reserved.
//
#define DLog(fmt, ...) NSLog((@"%s [Line %d] " fmt), __PRETTY_FUNCTION__, __LINE__, ##__VA_ARGS__)


#define BaseUrl             @"http://test.kelltontech.com/oxyfryer/index.php/webservice/"
//#define BaseUrl             @"http://www.oxyfryer.com/index.php/webservice/"
#define URL_getRecipeListing  @"getRecipeListing"
#define URL_getRecipeDetail   @"getRecipeDetail"
#define URL_getFAQListing     @"getFAQListing"
#define URL_sendFaqEmail      @"sendFaqEmail"
#define URL_registration      @"registration"
#define URL_UploadRecipe      @"UploadRecipe"

#define dummy_api_token    @"442d3d2e505d4a643e4f6a772f"
#define api_token          @"api_token"
#define api_version        @"api_version"
#define KEY_api_call       @"api_call"
#define VALUE_api_version  @"1.0"
#define KEY_recipeID           @"recipeID"
#define KEY_ID             @"rp_id"
#define KEY_featured_image_url  @"rp_image_url"
#define KEY_post_modified_gmt @"rp_modified_on"
#define KEY_recipe_category @"rp_category"
#define KEY_recipe_maximum_cooking_time @"rp_max_cook_time"
#define KEY_recipe_maximum_preparation_time @"rp_max_preparation_time"
#define KEY_recipe_minimum_cooking_time @"rp_min_cook_time"
#define KEY_recipe_minimum_preparation_time @"rp_min_preparation_time"
#define KEY_recipe_quantity @"rp_quantity"
#define KEY_recipe_title   @"rp_name"
#define KEY_recipe_type    @"rp_type"
#define KEY_recipe_youtube_url @"rp_youtube_url"
#define KEY_ErrorCode      @"ErrorCode"
#define KEY_ErrorMessage   @"ErrorMessage"
#define KEY_Data           @"Data"
#define KEY_faq_answer     @"faq_answer"
#define KEY_faq_category   @"faq_category"
#define KEY_faq_question   @"faq_question"
#define KEY_Name           @"userName"
#define KEY_EmailAddress   @"userEmail"
#define KEY_ContactNumber  @"userPhone"
#define KEY_Message        @"userMessage"
#define KEY_rp_min_preparation_time @"rp_min_preparation_time"
#define KEY_rp_max_preparation_time @"rp_max_preparation_time"
#define KEY_rp_quantity    @"rp_quantity"
#define KEY_rp_max_cook_time @"rp_max_cook_time"
#define KEY_rp_category    @"rp_category"
#define KEY_rp_description @"rp_description"
#define KEY_rp_image_url   @"rp_image_url"
#define KEY_rp_ingredients @"rp_ingredients"
#define KEY_rp_type        @"rp_type"
#define KEY_rp_min_cook_time @"rp_min_cook_time"
#define KEY_rp_modified_on  @"rp_modified_on"
#define KEY_rp_name         @"rp_name"
#define KEY_rp_id           @"rp_id"
#define KEY_rp_youtube_url   @"rp_youtube_url"
#define KEY_rp_temprature    @"rp_temprature"
#define KEY_alert          @"alert"
#define KEY_aps            @"aps"
#define KEY_result         @"result"
#define KEY_apnsType       @"apnsType"
#define KEY_deviceToken    @"deviceToken"
#define KEY_platform       @"platform"
#define KEY_osVersion      @"osVersion"
#define KEY_deviceModel    @"deviceModel"
#define KEY_UP_fullName    @"fullName"
#define KEY_UP_email       @"email"
#define KEY_UP_number      @"number"
#define KEY_UP_dishName    @"dishName"
#define KEY_UP_minCookTime @"minCookTime"
#define KEY_UP_maxCookTime @"maxCookTime"
#define KEY_UP_maxPrepTime @"maxPrepTime"
#define KEY_UP_quantity       @"quantity"
#define KEY_UP_ingredients    @"ingredients"
#define KEY_UP_howToUse    @"howToUse"
#define KEY_UP_category       @"category"
#define KEY_UP_type           @"type"
#define KEY_UP_temprature     @"temprature"
#define KEY_UP_image          @"image"
#define KEY_UP_youtubeVideo   @"youtubeVideo"
#define KEY_deviceTagstrip    @"deviceTagstrip"
#define NOTI_PUSHNOTIF         @"Noti_Push"
